name: Alpha

on:
  push:
    branches: [master]

jobs:
  main:
    name: Check & Deploy
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      SKIP_CI: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        if: ${{ !$SKIP_CI }}
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2

      - name: Install
        run: npm install

      - name: Check Linting
        if: ${{ !$SKIP_CI }}
        run: npm run lint

      - name: Build
        run: npm run build:alpha

      - name: Deploy
        run: npm run deploy:alpha -- --token "$FIREBASE_TOKEN"
