name: Beta

on:
  push:
    branches: [beta]

jobs:
  main:
    name: Test, Deploy & Pre-Release
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2
        with:
          ref: beta
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Install
        run: npm install

      - name: Check Linting
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:ci

      - name: Run e2e Tests
        run: npm run e2e

      - name: Prepare Pre-Release
        run: |
          git fetch
          git config user.name "GitHub Actions"
          git config user.email "yashanand1910@gmail.com"
          npm run release:beta
          git push origin beta --follow-tags
          git checkout master
          git merge beta
          git push origin master

      - name: Deploy
        run: npm run deploy:beta -- --token "$FIREBASE_TOKEN"

      - id: get_version
        name: Get Version
        uses: battila7/get-version-action@v2

      - name: Pre-Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          prerelease: true
