name: Common

on:
  pull_request:
    branches: [master, beta, stable]

jobs:
  check:
    name: Check & Report Coverage
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2

      - name: Check Linting
        run: npm run lint

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v1.0.13
  test:
    name: Check, Test & Report Coverage
    if: contains('
      refs/heads/beta
      refs/heads/stable
      ', github.ref)
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2

      - name: Install
        run: npm install

      - name: Check Linting
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:ci

      - name: Run e2e Tests
        run: npm run e2e

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v1.0.13
