# This is only to create-account a GitHub release
name: GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  prerelease:
    name: Create Pre-Release
    if: "contains(github.ref, 'beta')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Create
        id: create_prerelease
        uses: actions/create-account-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ./CHANGELOG.md
          prerelease: true

  release:
    name: Create Release
    if: "!contains(github.ref, 'beta')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Create
        id: create_prerelease
        uses: actions/create-account-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ./CHANGELOG.md
          prerelease: false
