# This workflow is only to create a GitHub release with notes
name: GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  prerelease:
    name: Create Pre-Release
    if: "contains(github.ref, 'beta')"
    runs-on: ubuntu-latest

    steps:
      - name: Generate release notes
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2
      - name: Create
        id: create_prerelease
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: true

  release:
    name: Create Release
    if: "!contains(github.ref, 'beta')"
    runs-on: ubuntu-latest

    steps:
      - name: Generate release notes
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2
      - name: Create
        id: create_prerelease
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
