name: Stable

on:
  push:
    branches: [stable]

jobs:
  main:
    name: Test, Deploy & Release
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2.3.2
        with:
          ref: stable
          token: ${{ secrets.ACTIONS_TOKEN }}
          fetch-depth: 0

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.4.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Stable

      - name: Install
        run: npm install

      - name: Check Linting
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run lint

      - name: Run Unit Tests
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run test:ci

      - name: Run e2e Tests
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: npm run e2e

      - name: Build
        run: npm run build

      - name: Prepare Release
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        run: |
          git fetch --all
          git config user.name "GitHub Actions"
          git config user.email "yashanand1910@gmail.com"
          npm run release
          git checkout beta
          git merge stable --allow-unrelated-histories
          git checkout master
          git merge beta --allow-unrelated-histories
          git push --follow-tags origin stable
          git push origin beta
          git push origin master

      - name: Deploy
        run: npm run deploy -- --token "$FIREBASE_TOKEN"

      - name: Finish Deployment
        uses: bobheadxi/deployments@v0.4.2
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://rozgar.today

      - id: get_version
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        name: Get Version
        uses: battila7/get-version-action@v2

      - name: Release
        if: "!contains(github.event.head_commit.message, 'chore(release)')"
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
